package:
  name: snack
  version: "0.0.3"

source:
  path: ".."

build:
  # noarch_python: True
  # preserve_egg_dir: True
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - numpy
    - cython
    - openblas # [not osx]
    - gcc # [osx]

  run:
    - python
    - numpy
    - openblas # [not osx]
    - gcc # [osx]

about:
  home: http://vision.cornell.edu/se3/projects/concept-embeddings/
  license: BSD 4-clause License
  summary: "Quick and dirty visualization of large-scale datasets via concept embeddings"

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
